export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const USER_UPDATE = "USER_UPDATE";

export const SET_SOCKET = "SET_SOCKET";

export const FETCH_CHATS = "FETCH_CHATS";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";

export const FRIENDS_ONLINE = "FRIENDS_ONLINE";
export const FRIEND_ONLINE = "FRIEND_ONLINE";
export const FRIENDS_OFFLINE = "FRIENDS_OFFLINE";

export const RECEIVED_MESSAGES = "RECEIVED_MESSAGES";
export const SENDER_TYPING = "SENDER_TYPING";
export const PAGINATE_MESSAGES = "PAGINATE_MESSAGES";
export const INCREMENT_SCROLL = "INCREMENT_SCROLL";
